### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by LeeluPradhan** [architdate/PSARipper#4]
Full error:
```
C:\Users\sample\Downloads\Compressed\PSARipper>python PSA.py
Enter a PSA url - https://psarips.one/tv-show/rick-and-morty/
Enter download mode (latest/full/1080p/720p) - latest

Show: Rick and Morty
Rating: 4.7

Traceback (most recent call last):
  File "C:\Users\sample\Downloads\Compressed\PSARipper\psaripper\PSAEntry.py", line 22, in get_ddl_urls
    ddlurl = decrypt_url(ddl[1], self.scraper)
  File "C:\Users\sample\Downloads\Compressed\PSARipper\psaripper\util.py", line 40, in decrypt_url
    furl = base64.b64decode(urlt.split("url\' value=")[1].split('/>')[0].strip()).decode('utf-8')
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PSA.py", line 57, in <module>
    ddlurls = media.get_ddl_urls()
  File "C:\Users\sample\Downloads\Compressed\PSARipper\psaripper\PSAEntry.py", line 28, in get_ddl_urls
    ddlurl = decrypt_url(ddl[1], self.scraper)
  File "C:\Users\sample\Downloads\Compressed\PSARipper\psaripper\util.py", line 40, in decrypt_url
    furl = base64.b64decode(urlt.split("url\' value=")[1].split('/>')[0].strip()).decode('utf-8')
IndexError: list index out of range
```

**Comment by architdate** [comment]
They patched this method already. I put up a notice in my readme. Couldn't find a solution after trying to break it again for like 40 minutes. I'll try to break it again when I have the time

**Comment by LeeluPradhan** [comment]
hey @architdate can [universal bypass](https://github.com/Sainan/Universal-Bypass) added to it? 
It will be hassle free!

**Comment by architdate** [comment]
Universal bypass seems to be one way, but their crowd bypass api is closed source unfortunately. I'll still attempt to add it though by looking at how the extension interacts with their api in Burp Suite or something

**Comment by LeeluPradhan** [comment]
Yes, universal bypass is our last hope!

**Comment by sherlockia** [comment]
@architdate  Bro, any update on this. Did you find another way to bypass?

**Comment by W-Floyd** [comment]
fwiw, Universal Bypass does not work for links on PSARips (or at least, not all of the chained links).

**Comment by architdate** [comment]
This works again now
